import Link from 'next/link'
import { Playfair_Display } from 'next/font/google'
import { ArrowLeft, CalendarDays, CheckCircle2, Phone, ShieldCheck } from 'lucide-react'
import Header from '@/app/components/Header'
import Footer from '@/app/components/Footer'

const playfairDisplay = Playfair_Display({ subsets: ['latin'] })

export default function SignatureTreatmentPage({ eyebrow, title, description, about, concerns, benefits, steps, aftercare, image, Icon, aboutHeading = 'Care guided by your needs', journeyHeading = 'A measured approach, at every step.' }) {
  return <main className={`${playfairDisplay.className} min-h-screen bg-white text-[#1A1A2E]`}><Header />
    <section className="bg-gradient-to-br from-[#FFF5F8] via-white to-[#F0F7FF] py-14 lg:py-20"><div className="mx-auto max-w-6xl px-5 lg:px-8"><Link href="/treatments" className="inline-flex items-center gap-2 text-sm font-bold text-[#D4146A] hover:underline"><ArrowLeft className="h-4 w-4" /> Back to Treatments</Link><div className="mt-9 grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><span className="inline-flex items-center gap-2 rounded-full bg-[#FFF0F6] px-4 py-2 text-xs font-bold uppercase tracking-wider text-[#D4146A]"><Icon className="h-4 w-4" />{eyebrow}</span><h1 className="mt-5 text-4xl font-bold leading-tight md:text-6xl">{title}</h1><p className="mt-6 max-w-xl text-lg leading-relaxed text-[#5A5A72]">{description}</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/book-appointment" className="inline-flex items-center gap-2 rounded-xl bg-[#D4146A] px-6 py-3.5 text-sm font-bold text-white"><CalendarDays className="h-4 w-4" />Book Consultation</Link><a href="tel:+919417237526" className="inline-flex items-center gap-2 rounded-xl border border-[#1A1A2E]/15 bg-white px-6 py-3.5 text-sm font-bold"><Phone className="h-4 w-4" />Call Now</a></div></div><div className="relative overflow-hidden rounded-3xl bg-[#F7F9FC] shadow-xl"><img src={image} alt={title} className="h-80 w-full object-cover md:h-[430px]" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#1A1A2E]/70 to-transparent p-7"><p className="text-xs font-bold uppercase tracking-[0.18em] text-[#F3C56B]">Doctor-led care</p><p className="mt-2 text-lg font-bold text-white">Personalised to your concern</p></div></div></div></div></section>
    <section className="py-16"><div className="mx-auto grid max-w-6xl gap-10 px-5 lg:grid-cols-[1.1fr_.9fr] lg:px-8"><div><p className="text-sm font-bold uppercase tracking-widest text-[#D4146A]">About this service</p><h2 className="mt-3 text-3xl font-bold">{aboutHeading}</h2><p className="mt-5 leading-8 text-[#5A5A72]">{about}</p></div><div className="rounded-2xl bg-[#FAFBFD] p-7"><h2 className="text-xl font-bold">This may help with</h2><ul className="mt-5 space-y-4">{concerns.map((concern) => <li key={concern} className="flex gap-3 text-sm text-[#5A5A72]"><CheckCircle2 className="h-5 w-5 shrink-0 text-[#D4146A]" />{concern}</li>)}</ul></div></div></section>
    <section className="bg-[#FAFBFD] py-16"><div className="mx-auto max-w-6xl px-5 lg:px-8"><div className="max-w-2xl"><p className="text-sm font-bold uppercase tracking-widest text-[#D4146A]">Your consultation experience</p><h2 className="mt-3 text-3xl font-bold">{journeyHeading}</h2></div><div className="mt-9 grid gap-4 md:grid-cols-3">{steps.map((step, index) => <div key={step} className="rounded-2xl bg-white p-6 shadow-sm ring-1 ring-[#EEF0F4]"><span className="text-sm font-bold text-[#D4146A]">0{index + 1}</span><p className="mt-5 text-base font-bold">{step}</p></div>)}</div><div className="mt-8 flex items-start gap-3 rounded-2xl border border-[#F0D3DF] bg-[#FFF8FB] p-5"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#D4146A]" /><div><h3 className="font-bold">Before and after your visit</h3><p className="mt-1 text-sm leading-6 text-[#5A5A72]">{aftercare}</p></div></div></div></section>
    <section className="bg-white px-5 pb-16 lg:px-8"><div className="mx-auto flex max-w-6xl flex-col items-start justify-between gap-6 rounded-3xl bg-[#D4146A] p-8 text-white md:flex-row md:items-center md:p-10"><div><h2 className="text-2xl font-bold">Ready to discuss your concerns?</h2><p className="mt-2 text-white/85">Book a private consultation with our dermatologist.</p></div><Link href="/book-appointment" className="inline-flex items-center gap-2 rounded-xl bg-white px-6 py-3 font-bold text-[#D4146A]"><CalendarDays className="h-4 w-4" />Book Appointment</Link></div></section><Footer />
  </main>
}
